<a href="https://colab.research.google.com/github/Ngom/My_Codes_Dsti/blob/main/BertTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BERT EMBEDING WITH TENSORFLOW - NLP

In [37]:
# Import needed libraries
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
#!pip3 install tensorflow_text || install it first if not yet 

In [38]:
# The separate preprocessor transforms plain text inputs into this format
preprocessing_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
# It uses L=12 hidden layers (i.e., Transformer blocks), a hidden size of H=768, and A=12 attention heads. 
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3'

In [39]:
# Get preprocessing model
bert_preprocessor_model = hub.KerasLayer(preprocessing_url) # It works like a function

In [40]:
# define two sentences to make a test
text_test = ["I love Python and TensorFlow", "I love Football and science books"]

In [41]:
# get the preprocessed output wich is a dictionnary
preprocessed_text = bert_preprocessor_model(text_test) 
# get the keys
preprocessed_text.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [42]:
# get 'input_mask' value
preprocessed_text['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [43]:
# get 'input_type_ids' value
preprocessed_text['input_type_ids']
# "CLS I love Python and TensorFlow SEP" how the sentence is handled 

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [44]:
# get 'input_word_ids' value
preprocessed_text['input_word_ids']
# "CLS I love Football and science books SEP" how the sentence is handled

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  1045,  2293, 18750,  1998, 23435, 12314,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [45]:
# Get a BERT encoder model now
encoder_model = hub.KerasLayer(encoder_url) # It works as well like function
# Get the embeded vectors of the text with BERT
results = encoder_model(preprocessed_text)

In [46]:
# get the keys of outpu dict()
results.keys()

dict_keys(['pooled_output', 'default', 'sequence_output', 'encoder_outputs'])

In [47]:
# give the entire sentence embeding vectors
results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8995526 , -0.53563184, -0.91199446, ..., -0.8257045 ,
        -0.72207093,  0.92192906],
       [-0.8957446 , -0.5166899 , -0.93175995, ..., -0.7261993 ,
        -0.70532745,  0.89629906]], dtype=float32)>

In [48]:
# individual word embeding vectors
results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.11107904,  0.08823845, -0.22717202, ..., -0.13230506,
          0.23241182,  0.7932381 ],
        [ 0.43959874,  0.15172824, -0.5375718 , ...,  0.09262419,
          0.5756407 ,  0.38291195],
        [ 1.1082827 ,  1.010008  ,  0.16809574, ...,  0.08841606,
          0.46047807,  0.23622651],
        ...,
        [ 0.11140769, -0.22311157,  0.594194  , ...,  0.25102407,
         -0.10382501,  0.06807792],
        [ 0.07217257, -0.17395358,  0.5959266 , ...,  0.19067466,
         -0.1288271 ,  0.08898591],
        [ 0.12408911, -0.23401661,  0.59603614, ...,  0.20183906,
         -0.16713932,  0.03381419]],

       [[-0.03751505,  0.15176015, -0.28256863, ..., -0.1215978 ,
          0.54419386,  0.33422616],
        [ 0.5632213 ,  0.34896106, -0.6882528 , ...,  0.03490664,
          1.0032347 ,  0.27804205],
        [ 1.2898139 ,  0.8960895 ,  0.18848741, ...,  0.24121141,
          0.6254553 , -0.05480304],
        ...,

In [49]:
# encoder size, here 12, is ther BERT base model used here.
len(results['encoder_outputs'])

12

In [50]:
 # see first layer output for instance
results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.10128601,  0.00910403, -0.07357201, ...,  0.10275798,
         -0.01996173, -0.04673342],
        [ 0.5640932 ,  0.75005007, -0.18127131, ...,  0.5308089 ,
          0.7475175 , -0.11824881],
        [ 1.3730402 ,  0.6226032 ,  0.17862754, ...,  0.46330512,
          0.53056574, -0.17267212],
        ...,
        [ 0.07695344, -0.25388774,  0.52457404, ..., -0.06655112,
         -0.47931132,  0.0311451 ],
        [-0.01111346, -0.27147576,  0.36722544, ..., -0.00743643,
         -0.3897387 , -0.06636477],
        [ 0.16202378, -0.21057446,  0.3803922 , ...,  0.35277206,
         -0.7319173 , -0.16098809]],

       [[ 0.15216477,  0.03098228, -0.05242228, ...,  0.12761122,
          0.00197702,  0.00705219],
        [ 0.5581813 ,  0.8642176 , -0.18555844, ...,  0.56418526,
          0.68112606,  0.07197824],
        [ 1.5002285 ,  0.47494358,  0.63678074, ...,  0.4426347 ,
          0.8235208 , -0.01050968],
        ...,

In [51]:
# The sequence_output is also the last vector of encoder_output
results['encoder_outputs'][-1] == results['sequence_output'] # this captures the context sense of each word

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

## E-mail Classification with BERT as encoder

[Bert]('/content/drive/MyDrive/ColabNotebooks/bert_spam.png', 'image')

In [52]:
# Define a BERT embeding function below
def get_sentence_embeding(sentence):
  # Get the preprocessor
  bert_preprocessor = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3') 
  # Get the preprocessed output
  preprocessed_text = bert_preprocessor_model(sentence) 
  # Get the BERT encoder
  bert_encoder = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3')
  # return entire sentence embeding vectors maker with ('pooled_output')
  return bert_encoder(preprocessed_text)['pooled_output'] 

In [54]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

## Get embeding vectors for few sample words. Compare them using cosine similarity

In [55]:
emb = get_sentence_embeding([
    "banana", 
    "tomato",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [58]:
emb[0][:10] # ten firs items

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.7606917 , -0.14219375,  0.49604657,  0.5634575 , -0.32544863,
       -0.10426541,  0.86149526,  0.15325738,  0.23656581, -0.9989279 ],
      dtype=float32)>

In [70]:
emb[2][:10] # ten firs items

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.7128861 , -0.154639  ,  0.38401696,  0.5236993 , -0.40326795,
       -0.02961858,  0.82174104,  0.18807201,  0.1459225 , -0.99867284],
      dtype=float32)>

In [61]:
# Similary check banana and mango
cosine_similarity([emb[0]], [emb[2]])

array([[0.9954098]], dtype=float32)

In [62]:
# Similary check banana and tomato
cosine_similarity([emb[0]], [emb[1]])

array([[0.977188]], dtype=float32)

In [65]:
# Similary check banana and Jeff bezos
cosine_similarity([emb[0]], [emb[3]])

array([[0.84703845]], dtype=float32)

In [69]:
# Similary check elon musk and Jeff bezos
cosine_similarity([emb[4]], [emb[3]])

array([[0.98720354]], dtype=float32)

Notebook link 

[Link](https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/master/47_BERT_text_classification/BERT_email_classification.ipynb)