<a href="https://colab.research.google.com/github/Ngom/My_Codes_Dsti/blob/main/Python_Lab_II_complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Question 1:**  ...should you choose to accept it*
You are supposed to write an algorithm to dehaze images.<br>
You are given this paper:
https://arxiv.org/pdf/1601.07661.pdf
* What is this website ?
* What are the main takeaway ideas ?
* Which field of AI is it dealing with ?
* Do you have coffee nearby ?


**Answers:**
* This website hosts research papers. In terms of AI, go to **arXiv**
* The topic is **image dehazing**: in output we have a hazy image, we want to have a clean image at the end --> they trained a **CNN model**
* CNN model: non linear regression, we want to estimate the **transmission map t(x)**, that can be then used to recover the clean image
* It seems to work b/c they show beautiful images at the end
* Other paper: https://www.hindawi.com/journals/ijcgt/2014/308629/

###**Question 2:** *It all starts with a git clone*
<br>You come across this repository:
* https://github.com/thuBingo/DehazeNet_Pytorch

Like always the code is not commented
  * Where do you start ?

* Read the Readme file: we expect comments on the code, explainations on how to use the code, a description of the librairies, requirements.txt, etc


In [ ]:
# Command to generate the requirements.txt file:
!pip freeze > requirements.txt

In [ ]:
#View the concent of requirements.txt
!cat requirements.txt

In [ ]:
#Command to install libraries from a requirements.txt file
!pip install -r requirements.txt

In [ ]:
# Clone a repository
!git clone https://github.com/thuBingo/DehazeNet_Pytorch

Cloning into 'DehazeNet_Pytorch'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 22 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.


In [ ]:
# Move to DehazeNet_Pytorch folder 
%cd /content/DehazeNet_Pytorch

/content/DehazeNet_Pytorch


### **Question 3:** *relative paths, absolute paths...*
* What is relative path vs hardcoded path ? Should you use one 


vs the other?
* Can you comment the code and make it usable with relative paths

**Answers:**
* Hardcoded paths doesn't have any flexibility and comes from the root directory while the relative path is flexible and takes the last folders we are interested in. The relative path can be shared to other users

**Remarks:**
* Always add comments, docstrings to your code 

In [ ]:
# Import the create_dataset function: from <module> import <function>
# When we write code, try to name functions and modules differently
# Make sure that the module is located in the working directory (%cd)
from create_dataset import create_dataset

In [ ]:
# Create a directory with a few images
!mkdir /content/DehazeNet_Pytorch/img
!mkdir /content/DehazeNet_Pytorch/train_set

mkdir: cannot create directory ‘/content/DehazeNet_Pytorch/img’: File exists


In [ ]:
!wget 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/close-up-of-red-rose-royalty-free-image-672727875-1546363000.jpg'
!wget 'https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png'
!wget 'https://m0.her.ie/wp-content/uploads/2018/01/07093633/GettyImages-887815620.jpg'

In [ ]:
pwd

'/content/DehazeNet_Pytorch'

In [ ]:
# Call the function create_dataset
img_dir = '/content/DehazeNet_Pytorch/img'
data_dir = '/content/DehazeNet_Pytorch/train_set'
create_dataset(img_dir, data_dir, num_t=10, patch_size=16)

AttributeError: ignored

###**Question 4:** *the good hunter and the bad hunter*

All the code is in 1 file (DehazeNet-pytorch.py), how can we re-organize the code?
Can we reorganize it in 3 files ?
  * data processing
  * model training
  * model evaluation
  * How are you going to deal with the imports?

**Answers:**
We should create a folder (a package), in which we will put our 3 functions

In [ ]:
import shutil
shutil.rmtree('/content/DehazeNet_Pytorch/train_set', ignore_errors=True)
# pour détruire un directory et toute son arborescence.

In [ ]:
# Create a folder named Dehazing_functions
!mkdir /content/DehazeNet_Pytorch/Dehazing_functions

In [ ]:
# Create an empty file
!touch /content/DehazeNet_Pytorch/Dehazing_functions/data_processing.py
!touch /content/DehazeNet_Pytorch/Dehazing_functions/model_training.py
!touch /content/DehazeNet_Pytorch/Dehazing_functions/model_evaluation.py

In [ ]:
!touch /content/DehazeNet_Pytorch/Dehazing_functions/custom_transform.py
!touch /content/DehazeNet_Pytorch/Dehazing_functions/config.py

In [ ]:
## Import all the functions we created
import Dehazing_functions.config
import Dehazing_functions.custom_transform

In [ ]:
import Dehazing_functions.data_processing

In [ ]:
import Dehazing_functions.model_evaluation

In [ ]:
import Dehazing_functions.model_training

###**Question5** : *Don't worry if you don't understand Andrew NG*

When it comes to dehazing there are 5 relevant features
* According to the paper what are these relevant features ?

How to read one paper (Andrew NG) ?<br>
**Don't start from the first page and finish at last one
Read it in multiple passes**<br>
1. Read the title, abstracts, figures, experiments
2. Go through conclusion, Figures and skip the rest
3. Read the rest but skip the math
4. Read whole but skip the parts that don't make sense.

###**Question 6:** *What did I just read?*
* According to what you have read
  * What is the goal of the neural network -
classification ? regression ?
  * according to the code  What is the goal of the code - classification ? regression ?

__Answers__:

* The neural netwok goal is classification

* The goal code of this CNN is classifaction

###**Question7**: *a bit of jargon*
<br>
(Please provide an example for each question)

* What is a "weights" file ? 

* What is a pickle file ?

* What is *defog4_noaug.pth* ?

**Answers:**
- In any model, we want to save the weights (set of parameters) of the model. 
- Pickling: Save the model in a binary format, a tool to load the weights

**Question 8:** *good code is like art... or not*
<br>
In the defog function below you can see many statements:
* Can you explain what the function actually does ?
* Is it an efficient way to write code ?
* what does the code below mean ?
* Can you propose a more efficient way ? no more for loop ?
https://stackoverflow.com/questions/31527755/extract-blocks-or-patches-from-numpy-array


### Some numpy practice

In [ ]:
import numpy as np
A= np.array(range(625)).reshape(25,25)
# Print a slice of matrix A - every fifth element by row and column
print(A[::5,::5])

[[  0   5  10  15  20]
 [125 130 135 140 145]
 [250 255 260 265 270]
 [375 380 385 390 395]
 [500 505 510 515 520]]


In [ ]:
# Inspect the first row of the matrix
# This notation returns a matrix
print(A[:1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [ ]:
# Inspect the first row of the matrix
# This notation returns a vector
print(A[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
# Inspect the first two columns of the matrix
print(A[:,:2])

[[  0   1]
 [ 25  26]
 [ 50  51]
 [ 75  76]
 [100 101]
 [125 126]
 [150 151]
 [175 176]
 [200 201]
 [225 226]
 [250 251]
 [275 276]
 [300 301]
 [325 326]
 [350 351]
 [375 376]
 [400 401]
 [425 426]
 [450 451]
 [475 476]
 [500 501]
 [525 526]
 [550 551]
 [575 576]
 [600 601]]


In [ ]:
# Transpose the first two columns of the matrix
A[:,:2].transpose()

array([[  0,  25,  50,  75, 100, 125, 150, 175, 200, 225, 250, 275, 300,
        325, 350, 375, 400, 425, 450, 475, 500, 525, 550, 575, 600],
       [  1,  26,  51,  76, 101, 126, 151, 176, 201, 226, 251, 276, 301,
        326, 351, 376, 401, 426, 451, 476, 501, 526, 551, 576, 601]])

In [ ]:
A[:,:2].T # gives the transpose 

In [ ]:
# View the dimensions of the matrix by the 'shape' attribute
# Note: You get a 'tuple is not callable' error if you try to 
# call an attribute as method
A.shape

(25, 25)

## Back to the problem: Extracting patches from an image

First try: https://stackoverflow.com/a/31572112

In [ ]:
# Use a Scikit utility to generate the patches
from skimage.util import view_as_blocks

In [ ]:
# Use the view_as_blocks function on the test matrix A
view_as_blocks(A, (5, 5))

In [ ]:
# Check the return type of view_as_blocks
test = view_as_blocks(A, (5, 5))
type(test)

numpy.ndarray

In [ ]:
# View the shape of the returned numpy object
test.shape

(5, 5, 5, 5)

In [ ]:
# Reshape the ndarray to get batches of size 25 in a 5x5 matrix
reshaped_test = test.reshape(25,5,5)

In [ ]:
# Confirm the reshaped object has the expected dimensions
reshaped_test.shape

(25, 5, 5)

In [ ]:
# Confirm the first batch matches the top 5x5 matrix
reshaped_test[0]

array([[  0,   1,   2,   3,   4],
       [ 25,  26,  27,  28,  29],
       [ 50,  51,  52,  53,  54],
       [ 75,  76,  77,  78,  79],
       [100, 101, 102, 103, 104]])

In [ ]:
# Test iteration over ndarray
for k in range(3):
    print(reshaped_test[k])

[[  0   1   2   3   4]
 [ 25  26  27  28  29]
 [ 50  51  52  53  54]
 [ 75  76  77  78  79]
 [100 101 102 103 104]]
[[  5   6   7   8   9]
 [ 30  31  32  33  34]
 [ 55  56  57  58  59]
 [ 80  81  82  83  84]
 [105 106 107 108 109]]
[[ 10  11  12  13  14]
 [ 35  36  37  38  39]
 [ 60  61  62  63  64]
 [ 85  86  87  88  89]
 [110 111 112 113 114]]


Let's attempt the above transformation on a simulated RGB image, since our actual problem requires us to work on ... an RGB image.

In [ ]:
# Import OpenCV
import cv2

In [ ]:
# Simulate an RGB image based on the ndarray we generated before
A_rgb = cv2.merge([A,A,A])

In [ ]:
# Inspect the shape of our simulated image
A_rgb.shape

(25, 25, 3)

In [ ]:
A_rgb[0,1]

array([1, 1, 1], dtype=int32)

In [ ]:
# Convert the simulated images into blocks
A_rgb_in_blocks = view_as_blocks(A_rgb, (5, 5, 1))

In [ ]:
A_rgb_in_blocks

In [ ]:
A_rgb_in_blocks.shape

(5, 5, 3, 5, 5, 1)

In [ ]:
# Try to reshape the image into a useable form
A_rgb_in_blocks.reshape(-1,5,5)

Since we can't find a way to make this work with all three image channels simultaneously, we'll divide and conquer and process channel by channel.

In [ ]:
# re-create the simulated A_rgb image
A_rgb = cv2.merge([A,A,A])

In [ ]:
A_rgb.shape

(25, 25, 3)

In [ ]:
# Seperate the three channels
A_red, A_green, A_blue = A_rgb[:,:,0], A_rgb[:,:,1], A_rgb[:,:,2]

# The above code is shorthand for:
#
# A_red = A_rgb[:,:,0]
# A_green = A_rgb[:,:,1]
# A_blue = A_rgb[:,:,2]

In [ ]:
# Inspect the shape of our color channel arrays
A_red.shape

(25, 25)

In [ ]:
# Process each channel with the skimage function we used above
A_red_patches = view_as_blocks(A_red, (5, 5)).reshape(-1, 5, 5)
A_green_patches = view_as_blocks(A_green, (5, 5)).reshape(-1, 5, 5)
A_blue_patches = view_as_blocks(A_blue, (5, 5)).reshape(-1, 5, 5)

In [ ]:
# Inspect the re-shaped color channel arrays
A_red_patches.shape

(25, 5, 5)

In [ ]:
# Re-assemble the color channels 
stacked_patches = np.stack([A_red_patches, A_green_patches, A_blue_patches], axis=3)

In [ ]:
my_stacked_patch = stacked_patches[0]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Saving the image so we can inspect it. Note that to save an
# image in pyplot, it needs to be stored as 8-bit integer.
plt.imsave('testimage.jpg', my_stacked_patch.astype(np.uint8))

In [ ]:
A_red_patches[0]

array([[  0,   1,   2,   3,   4],
       [ 25,  26,  27,  28,  29],
       [ 50,  51,  52,  53,  54],
       [ 75,  76,  77,  78,  79],
       [100, 101, 102, 103, 104]], dtype=int32)

In [ ]:
# Process each channel with the skimage function we used above
A_red_patches_flat = view_as_blocks(A_red, (5, 5)).reshape(-1, 5, 5)
A_green_patches_flat = view_as_blocks(A_green, (5, 5)).reshape(-1, 5, 5)
A_blue_patches_flat = view_as_blocks(A_blue, (5, 5)).reshape(-1, 5, 5)

In [ ]:
vstacked_patches = np.stack([A_red_patches_flat, A_green_patches_flat, A_blue_patches_flat], axis=1)

In [ ]:
vstacked_patches.shape

(25, 3, 5, 5)

In [ ]:
vstacked_patches[0][:]

array([[[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  52,  53,  54],
        [ 75,  76,  77,  78,  79],
        [100, 101, 102, 103, 104]],

       [[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  52,  53,  54],
        [ 75,  76,  77,  78,  79],
        [100, 101, 102, 103, 104]],

       [[  0,   1,   2,   3,   4],
        [ 25,  26,  27,  28,  29],
        [ 50,  51,  52,  53,  54],
        [ 75,  76,  77,  78,  79],
        [100, 101, 102, 103, 104]]], dtype=int32)

We couldn't make this work for our 3d-array, so we'll investigate another response from Stackoverflow: https://stackoverflow.com/a/31529389

```
In [60]: x
Out[60]: 
array([[2, 1, 2, 2, 0, 2, 2, 1, 3, 2],
       [3, 1, 2, 1, 0, 1, 2, 3, 1, 0],
       [2, 0, 3, 1, 3, 2, 1, 0, 0, 0],
       [0, 1, 3, 3, 2, 0, 3, 2, 0, 3],
       [0, 1, 0, 3, 1, 3, 0, 0, 0, 2],
       [1, 1, 2, 2, 3, 2, 1, 0, 0, 3],
       [2, 1, 0, 3, 2, 2, 2, 2, 1, 2],
       [0, 3, 3, 3, 1, 0, 2, 0, 2, 1]])

In [61]: result1 = x.reshape(x.shape[0]//2, 2, x.shape[1]//2, 2).swapaxes(1, 2).reshape(-1, 2, 2)
```

To better understand what is happening, we'll run the code part by part:

In [ ]:
A_rgb.shape

(25, 25, 3)

In [ ]:
test_1 = A_rgb.reshape(3, A_rgb.shape[0]//5, 5, A_rgb.shape[1]//5, 5)

In [ ]:
test_1.shape

(3, 5, 5, 5, 5)

In [ ]:
test_1_sliced = test_1[0][0][0][:][:]

In [ ]:
test_1_sliced

array([[0, 0, 0, 1, 1],
       [1, 2, 2, 2, 3],
       [3, 3, 4, 4, 4],
       [5, 5, 5, 6, 6],
       [6, 7, 7, 7, 8]], dtype=int32)

In [ ]:
test_1_sliced[0]

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int32)

In [ ]:
test_2 = test_1.swapaxes(1, 2)

In [ ]:
test_2.shape

(5, 5, 5, 5, 3)

In [ ]:
test_2[0][0][:][:][:]

In [ ]:
test_3 = test_2.reshape(-1, 5, 5)

In [ ]:
test_3.shape

(75, 5, 5)

In [ ]:
test_3[0]

array([[ 0,  0,  0,  1,  1],
       [ 1,  2,  2,  2,  3],
       [ 3,  3,  4,  4,  4],
       [25, 25, 25, 26, 26],
       [26, 27, 27, 27, 28]], dtype=int32)

In [ ]:
from PIL import Image
from skimage.util import view_as_blocks

def defog(pic_dir):
	img = Image.open(pic_dir)
	img1 = loader(img)
	img2 = transforms.ToTensor()(img)
	c, h, w = img1.shape
	patch_size = 16
	num_w = int(w / patch_size)
	num_h = int(h / patch_size)
	
	# Creating the patches

	# Separate color channels
	img2_red = img2[:,:,0]
	img2_green = img2[:,:,1]
	img2_blue = img2[:,:,2]

	# For each color channel, create the patches	
	A_red_patches = view_as_blocks(img2_red, (patch_size, patch_size)).reshape(-1, 5, 5)
	A_green_patches = view_as_blocks(img2_green, (patch_size, patch_size)).reshape(-1, 5, 5)
	A_blue_patches = view_as_blocks(img2_blue, (patch_size, patch_size)).reshape(-1, 5, 5)

	# Restack the color channels into colored patches
	img2_patches = np.stack([img2_red, img2_green, img2_blue], axis=3)

	# torch.unsqueeze() adds one dimension to 
	# patch = torch.unsqueeze(img2_patches, dim=0)
 	
	 # net takes an array of patches as input and will
	 # output an array of predicted t values. Note that
	 # we should not do any of these two things:

	 # (1) Send one patch after the other
	 # (2) Send all patches at once
	 
	 # Instead, we send the patches in batches and
	 # append the predictions in order to a new array.
	 # These values can be appened to an array. (note: note implemented)
	 t = net(img2_patches)
	
	# From the array of predictions, we compute the maximum 
	# alpha value.
	t_list = sorted(t_list, key=lambda t_list:t_list[2])
	a_list = t_list[:len(t_list)//100]
	
	a0 = 0
	
	for k in range(0,len(a_list)):
		patch = img2[:, 0 + a_list[k][1] * patch_size:patch_size + a_list[k][1] * patch_size,
				0 + a_list[k][0] * patch_size:patch_size + a_list[k][0] * patch_size]
		
		a = torch.max(patch)
		if a0 < a.item():
			a0 = a.item()
	
	for k in range(0,len(t_list)):
		img2[:, 0 + t_list[k][1] * patch_size:patch_size + t_list[k][1] * patch_size,
			0 + t_list[k][0] * patch_size:patch_size + t_list[k][0] * patch_size] = (img2[:,
			0 + t_list[k][1] * patch_size:patch_size + t_list[k][1] * patch_size,
			0 + t_list[k][0] * patch_size:patch_size + t_list[k][0] * patch_size] - a0*(1-t_list[k][2]))/t_list[k][2]
	
	defog_img = transforms.ToPILImage()(img2)
	#defog_img.save('/home/panbing/PycharmProjects/defog/test/test.jpg')


#defog('/home/panbing/PycharmProjects/defog/test/fogpic.jpg')

###**Question26:** Classes

We want to define a class "car" with colour and brand as attribute

In [ ]:
# Class definition
class Car():
  # Parameters to instantiate/create a 'car' object
  def __init__(self, brand='Peugeot', color='red', max_velocity=358):
    self.color  = color
    self.brand = brand
    self.max_velocity = max_velocity
    self.wheels = self.get_num_wheels()
    self.speed = self.get_speed()

  # Defining a method (function)
  def get_speed(self):
    if self.brand == 'Ferrari':
      self.speed = 250
    else:
      self.speed = 120
    return self.speed

  # Another method
  def get_num_wheels(self):
    self.wheels = 4
    return self.wheels

In [ ]:
# Instantiate a 'car' object
my_car = Car('Ferrari', 'Yellow')

In [ ]:
# Call the get_speed() method
my_car.get_speed()

250

In [ ]:
# Get the parameters of my_car: my_car.color, my_car.brand, my_car.speed, my_car.max_velocity, my_car.wheels
my_car.speed

250

In [ ]:
my_car.wheels

4

###**Question27 bis:**  Abstract classes

**Question 27**: *My second class*

* Have you heard of class inheritance ?$
* Let's define a class named **vehicle**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

* Let's define a class named **moto**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed
* Let's define a class named car
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

In [4]:
# Class definition
from abc import ABC, abstractmethod
class Vehicle(ABC):
  # Should not be initialized
  # Decorator: should be added above each function
  # An abstract method is a method that has a declaration but does not have an implementation
  @abstractmethod
  def get_wheels(self):
    pass
  # Another method with the decorator above
  @abstractmethod
  def get_speed(self):
    pass

In [5]:
# Defining a class that inherite from the Vehicle class
class Moto(Vehicle):
  def __init__(self , year, brand , color, max_velocity):
    # Parameters that are specific to Moto
    self.year = year
    self.color  = color
    self.brand = brand
    self.max_velocity = max_velocity
    self.wheels = self.get_wheels()
    self.speed = self.get_speed()

  # Defining a method (function) specific to Moto
  def get_speed(self):
    if self.brand == 'Toyota':
      self.speed = 300
    else:
      self.speed = 200
    return self.speed
    
  def get_wheels(self):
    self.wheels = 2
    return self.wheels

In [6]:
my_moto = Moto(2020, 'Toyota', 'red', 158)

In [7]:
my_moto.brand

'Toyota'

Extra question: Can we create a class based on an abstract class but 'pass' on a required method?

In [ ]:
# Define a new class
class Truck(Vehicle):
    def __init__(self, year, brand, color, max_velocity):
        self.year = year
        self.color  = color
        self.brand = brand
        self.max_velocity = max_velocity
        self.wheels = self.get_wheels()
        self.speed = self.get_speed()

    # Define speed as required by Vehicle
    def get_speed(self):
        pass
    
    # Define get_wheels as required by Vehicle
    def get_wheels(self):
        self.wheels = 2
        return self.wheels

In [ ]:
my_truck= Truck(1995, 'MAN', 'Red', 123)

In [ ]:
# Testing if my_truck has a speed attribute
my_truck.speed

# The code executes so there is a speed attribute but since the function 
# defininig it did not return anything, no value is returned.

In [ ]:
# Check the type of my_truck.speed, expect NoneType
type(my_truck.speed)

NoneType

Answer: Yes, we can pass on a method defined by an abstract class.

Extra question 2: Can we add methods not defined in the abstract class?

In [ ]:
# Define a new class
class Truck2(Vehicle):
    def __init__(self, year, brand, color, max_velocity):
        self.year = year
        self.color  = color
        self.brand = brand
        self.max_velocity = max_velocity
        self.wheels = self.get_wheels()
        self.speed = self.get_speed()
        self.capacity = self.get_capacity()

    # Define speed as required by Vehicle
    def get_speed(self):
        pass
    
    # Define get_wheels as required by Vehicle
    def get_wheels(self):
        self.wheels = 2
        return self.wheels

    # Define a new method 
    def get_capacity(self):
        self.capacity = 25
        return self.capacity

In [ ]:
# Testing if my truck can be created
my_truck2 = Truck2(1995, 'MAN', 'Red', 123)

In [ ]:
# Testing if my_truck2 has a capacity attribute
my_truck2.capacity

25

Answer: Yes, we can add additional methods to daugther classes.

---

**Question 09**: *one command that chnaged everything*
* One friend of ours is not 100% sure of his/her Docker skills& shell commands, can you explain what the commands below would do ?


In [ ]:
!git clone https://github.com/thuBingo/DehazeNet_Pytorch.git

Cloning into 'DehazeNet_Pytorch'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 22 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.


In [ ]:
cd /content/DehazeNet_Pytorch

/content/DehazeNet_Pytorch


In [ ]:
mkdir ./dataset

**Question 10:** *copy paste* 

* If you have not cloned  the project, please clone it. what command are you going to use ?
* Your dehazing function should work, how do you update your github  repository

**Question 11**: *kaggle and its open sea of datasets*

* You have been told that there is a great dataset of underwater images available on kaggle.
* How do you programmatically download it ?
* Where will you run this command ?
* Is there a problem with colab ?
if yes what is the solution ?

### Describe problem 1

### Describe  problem 2

**Question 12** *GUI, CLI... API*
* What is a CLI?
* What do you need to interact with kaggle CLI ?

In [ ]:
# vous uploadez le fichier kaggle.json dans le répertoire : /root/.kaggle
!mkdir /root/.kaggle/
!cp /content/kaggle.json /root/.kaggle/

**Question 13** *kaggle data*
* What are the commands below ?
* What is missing in the second cell ?

In [ ]:
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6

In [ ]:
kaggle competitions download -c tensorflow-great-barrier-reef

In [ ]:
!kaggle competitions download -c tensorflow-great-barrier-reef --force


100% 14.2G/14.2G [01:56<00:00, 86.4MB/s]
100% 14.2G/14.2G [01:56<00:00, 131MB/s] 


**Question 14** *deal with zip*
* Let's assume you unzipped the file in the **WRONG** folder:
  * which command can help you out ?
  * How do you zip a folder ?
  * How do you zip a file ?
  * How many files have you unzipped?
  * Where can you see this info?

In [ ]:
 /content/DehazeNet_Pytorch/*.jpg /content/DehazeNet_Pytorch/dataset/

**Question 15** "just import it"

* You want to try the commands in the code: *test.py* (supplied in the aforementionned Github repository)
  * Can you import it as a module ?
  * Do you have to be placed in a particular folder ? 

In [ ]:
import create_dataset

100%|██████████| 34/34 [01:11<00:00,  2.11s/it]


* If  you run create_dataset does it work ?

* If you import create_dataset, what happens?

**Question 16:** *important matter*
<br>About import and reload: say you've modified the .py file and you want to reload a cell :

* If you modify the code in the editor can you run python code in Jupyter without reloading ?
* Is there any python commands which let you reload automatically ?

**Question 17:** *module update*
* What is %load_ext autoreload ?
* What is %autoreload 2 ?

In [ ]:
%load_ext autoreload
%autoreload 2
import create_dataset

**Question 18:** *if name =='__main__'*
<br>
In the code you often see "if name =='__main__'. * Is it necessary ?
* what does it do. ?

* what does the command below do ?
  * what does -r mean ?
  * what does -f mean ?

**Question 19:** *with great power comes great responsability*

* Does this statement applies for the command below?
* What does it do ?

In [ ]:
!rm -rf  /content/DehazeNet_Pytorch/fogged_dataset

**Question 20:** *Python is so pythonesque*
* What is the language below ?
* What is it doing ?

In [ ]:
!ls /content/DehazeNet_Pytorch/fogged_dataset | wc -l

1064286


In [ ]:
!cat /content/DehazeNet_Pytorch/path_train.txt | head -10

/content/DehazeNet_Pytorch/fogged_dataset/11110008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/11310008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12110008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12410008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12610008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/12710008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13310008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13510008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13710008.jpg
/content/DehazeNet_Pytorch/fogged_dataset/13810008.jpg


In [ ]:
!echo "$(ls -d /content/DehazeNet_Pytorch/fogged_dataset| head -1)/$(ls /content/DehazeNet_Pytorch/fogged_dataset| head -1)" >adder.txt

In [ ]:
!cp "$(ls -d /content/DehazeNet_Pytorch/fogged_dataset| head -1)/$(ls /content/DehazeNet_Pytorch/fogged_dataset| head -1)" /content/DehazeNet_Pytorch/test

**Question 21** : *a matter of pixel values*
* You have generated the files and yet you can't see them.
* why is that ?
* How can you check a couple of files ?
* Which commands can you run ? (to see the n first files ?)

**Question 22:** *a matter of imports*

Can you import DehazeNet-pytorch.py ?
* If not why ?
* Does the code work ?
* Can you import a module when there is a mistake/typo?


**Question23**: *Getting them images*

* How to download random image on the  web ?
* What is PIL? 
> The Python Imaging Library adds image processing capabilities to your Python interpreter.
* How do you open an image with 
  * PIL ?
  * opencv ?
  * matplotlib ?

In [ ]:
!wget https://cdn.pixabay.com/photo/2019/12/03/20/51/fog-4671042_960_720.jpg

--2022-01-23 19:03:49--  https://cdn.pixabay.com/photo/2019/12/03/20/51/fog-4671042_960_720.jpg
Resolving cdn.pixabay.com (cdn.pixabay.com)... 104.18.20.183, 104.18.21.183, 2606:4700::6812:14b7, ...
Connecting to cdn.pixabay.com (cdn.pixabay.com)|104.18.20.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 135630 (132K) [image/jpeg]
Saving to: ‘fog-4671042_960_720.jpg’

fog-4671042_960_720 100%[===================>] 132.45K  --.-KB/s    in 0.02s   

2022-01-23 19:03:50 (5.67 MB/s) - ‘fog-4671042_960_720.jpg’ saved [135630/135630]



**Question 24**: *say import one more time*
<br>
You want to test the code on an image, will the code below work ?

In [ ]:
%load_ext autoreload
%autoreload 2
import DehazeNet_pytorch

/content/DehazeNet_Pytorch/DehazeNet_pytorch.py:45: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  if m.bias is not None:


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Question 24**: *AI detected*
* In the code, where is the predictive model declared ?
* We don't want to reexecute longparts of the code all the time, what should we do ? 
  * Is it a good practice to have the code separated in many parts?

**Question 25**: *Hardcoding for life*
* In the code, how is the destination path is defined ?
* Is it correct ?
* What is ARGPARSE ?
  * Can we add argparse parameters to make this code easier to run ?

**Question 25**: *time to smash that button*
<br>
<br>
You might be ready to execute the code.
* Is it working - are you running the code on Colab?
* Why is it not - What happened?

In [2]:
%load_ext autoreload
%autoreload 2
import DehazeNet_pytorch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


**Question 26**: *My first class*

* Let's define a class named car
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

Must-read : https://realpython.com/python-super/

**Question 27**: *My second class*

* Have you heard of class inheritance ?$
* Let's define a class named **vehicle**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

* Let's define a class named **moto**
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed
* Let's define a class named car
  * attributes = color,brand, max velocity
  * function = give the number of wheels, give the max speed

["Simple examples - in case you are stuck"](https://www.edureka.co/blog/inheritance-in-python/)

**Question 28**: *Torch class*
* here is the example
* how would you apply it to this particular example ?

In [ ]:
import os
import pandas as pd

from torchvision.io import read_image

# inherits from the Dataset class
class CustomImageDataset(Dataset):

    # init function will be executed when instnatiated
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)   # attributes
        self.img_dir = img_dir                            # attributes
        self.transform = transform                        # attributes
        self.target_transform = target_transform          # attributes

    # allows you to calculate the length of the instantiated Dataset
    def __len__(self):
        return len(self.img_labels)

    # allows you to  pick 1 element in the dataset
    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

**Question 29**: *Torch class*
* Here is the example
* How would you apply it to this particular example ?
* please look @ the example below

https://stanford.edu/~shervine/blog/pytorch-how-to-generate-data-parallel

https://medium.com/analytics-vidhya/pytorch-for-deep-learning-feed-forward-neural-network-d24f5870c18

**Question 30**: *Time to nut up or shut up*
* Launch the training !
