<a href="https://colab.research.google.com/github/Ngom/My_Codes_Dsti/blob/main/Python_Lab_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# clone DehazeNet repository from git hub:
!git clone https://github.com/thuBingo/DehazeNet_Pytorch

Cloning into 'DehazeNet_Pytorch'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 22 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.


In [ ]:
# show downloaded repository
%cd /content/DehazeNet_Pytorch

/content/DehazeNet_Pytorch


In [ ]:
!ls -a

.  ..  .config	DehazeNet_Pytorch  sample_data


In [ ]:
!pwd

/content/DehazeNet_Pytorch


In [ ]:
!cd /content/DehazeNet_Pytorch/
# import the code as module
# from create_dataset import create_dataset

In [ ]:
# create  directories to store da
!mkdir /content/DehazeNet_Pytorch/img
!mkdir /content/DehazeNet_Pytorch/dest

In [ ]:
%cd img/
!wget https://image.shutterstock.com/image-illustration/beautiful-aurora-universe-milky-way-260nw-1787056478.jpg

[Errno 2] No such file or directory: 'img/'
/content/DehazeNet_Pytorch/img
--2022-01-24 13:26:37--  https://image.shutterstock.com/image-illustration/beautiful-aurora-universe-milky-way-260nw-1787056478.jpg
Resolving image.shutterstock.com (image.shutterstock.com)... 54.192.86.46, 54.192.86.41, 54.192.86.18, ...
Connecting to image.shutterstock.com (image.shutterstock.com)|54.192.86.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21350 (21K) [image/jpeg]
Saving to: ‘beautiful-aurora-universe-milky-way-260nw-1787056478.jpg’

beautiful-aurora-un 100%[===================>]  20.85K  --.-KB/s    in 0s      

2022-01-24 13:26:38 (87.4 MB/s) - ‘beautiful-aurora-universe-milky-way-260nw-1787056478.jpg’ saved [21350/21350]



In [ ]:
%cd /content/DehazeNet_Pytorch/

/content/DehazeNet_Pytorch


In [ ]:
# create_dataset('img/', 'dest/', num_t=10, patch_size=16)

In [ ]:
!mkdir /content/DehazeNet_Pytorch/dehaze
!touch /content/DehazeNet_Pytorch/dehaze/evaluation.py
!touch /content/DehazeNet_Pytorch/dehaze/processing.py
!touch /content/DehazeNet_Pytorch/dehaze/training.py

# Classes in Python - Object Oriented Programming

### Question 26: My first class

In [ ]:
# we create class with two attributes and three methods
# class name start by an upper case
# a class blueprint
class Car:
  # initialization function and its attributes
  def __init__(self, color, brand, max_velocity):
    self.color = color
    self.brand = brand
    self.max_velocity = max_velocity
    # initialze the attribute wheels by getting value from get_numb_wheels()
    self.wheels = self.get_numb_wheels()

  # our firs method
  def get_speed(self):
    if self.brand == 'Ferrari':
      self.speed = 250
    else:
      self.speed = 120
    return self.speed

  # our second method
  def get_type(self):
    self.color = self.color.lower()
    if self.color == "blue":
      self.categ = 'Automatique'
    else:
      self.categ = 'Manuelle'
    return self.categ

  # our third method
  def get_numb_wheels(self):
    return 4

In [15]:
# a class blueprint
class Car2:
  # initialization function
  def __init__(self, color, brand, max_velocity):
    self.color = color
    self.brand = brand
    self.max_velocity = max_velocity

  # method one
  def get_speed(self):
    if self.brand == 'Ferrari':
      self.speed = 250
    else:
      self.speed = 120
    return self.speed
      
  # method two
  def get_type(self):
    if self.max_velocity <= 50:
      self.categ = 'Automatique'
    else:
      self.categ = 'Manuelle'
    return self.categ

In [16]:
# Instantiate a first Car2 object
my_car = Car2('Blue', 'Ferrari', 300)

In [17]:
my_car.color

'Blue'

In [18]:
my_car.brand

'Ferrari'

In [19]:
my_car.max_velocity

300

In [20]:
my_car.get_speed()

250

In [21]:
my_car.get_type()

'Manuelle'

In [22]:
# Instantiate a first Car2 object
mini_car = Car2('Green', 'Vovo', 45)

In [23]:
mini_car.get_type()

'Automatique'

In [ ]:
# Instantiate a second Car object
vehi = Car('Green', 'Peageot')

In [ ]:
vehi.get_type()

'Manuelle'

In [ ]:
vehi.get_spreed()

120

In [ ]:
vehi.color

'green'

In [ ]:
vehi.brand

'Peageot'

## Create a movie object with four attributes and one method

In [ ]:
class Movie:
  def __init__(self, title, released, actor, mtype):
    self.title = title
    self.released = released
    self.actor = actor
    self.mtype = mtype
  
  def get_affiche(self):
    print(f'This is {self.title} released in {self.released} and acted by {self.actor}.')

In [ ]:
film_a = Movie('The Matrix', 1998, 'Tom Hunks', 'Action')

In [ ]:
film_b = Movie('Casa de Papel', 2014, 'Jacque Long', 'Serie')

In [ ]:
film_a.actor

'Tom Hunks'

In [ ]:
film_b.actor

'Jacque Long'

In [ ]:
film_a.get_affiche()

This is The Matrix released in 1998 and acted by Tom Hunks.


In [ ]:
film_b.get_affiche()

This is Casa de Papel released in 2014 and acted by Jacque Long.


In [ ]:
film_a.mtype

'Action'

In [ ]:
film_b.mtype

'Serie'

## Question 27: Class inherance with __super()__ or __abstact method__.

In [7]:
# a class blueprint
class Vehicule:
  # initialization function
  def __init__(self, year):
    self.year = year

In [8]:
# Here we declare that the Moto class inherits form Vehicule class
class Moto(Vehicule):
  # Moto will have these attributes
  def __init__(self, year, color, brand, max_velocity):
    super().__init__(year)
    self.color = color
    self.brand = brand
    self.max_velocity = max_velocity
    # initialze the attribute wheels by getting value from get_numb_wheels()
    self.wheels = self.get_wheels()

    # our firs method
  def get_speed(self):
    if self.brand == 'Ferrari':
      self.speed = 250
    else:
      self.speed = 120
    return self.speed

    # our third method
  def get_wheels(self):
    return 2

In [ ]:
my_moto = Moto(2015, 'Red', 'Yamaha', 125)

'Yamaha'

In [10]:
my_moto.brand

'Yamaha'

In [9]:
my_moto.get_speed()

120

In [11]:
my_moto.color

'Red'

#### Abstract Base Classes

In [1]:
# Define Vehicule class
from abc import ABC, abstractmethod
class Vehicule(ABC):
  # should not be init

  # add decorator 
  @abstractmethod 
  def get_speed(self):
    pass
    
  # add decorator
  @abstractmethod  
  def get_wheels(self):
    pass

# Note : a Vehiecle can be a car, moto, truck bycle, .....

In [2]:
# Here we declare that the Moto class inherits form Vehicule class
class Moto(Vehicule):
  # Moto will have these attributes
  def __init__(self, year, color, brand, max_velocity):
    self.year = year
    self.color = color
    self.brand = brand
    self.max_velocity = max_velocity
    # initialze the attribute wheels by getting value from get_numb_wheels()
    self.wheels = self.get_wheels()

    # our firs method
  def get_speed(self):
    if self.brand == 'Ferrari':
      self.speed = 250
    else:
      self.speed = 120
    return self.speed

    # our third method
  def get_wheels(self):
    return 2

In [3]:
my_moto = Moto(2015, 'Red', 'Yamaha', 125)

In [4]:
my_moto.color

'Red'

In [5]:
my_moto.wheels

2

In [6]:
my_moto.get_wheels()

2

### Question 8: good code is like art... or not

In [ ]:
import numpy as np
A= np.array(range(625)).reshape(25,25)
print(A[::5,::5]) # Take element fith by fith

[[  0   5  10  15  20]
 [125 130 135 140 145]
 [250 255 260 265 270]
 [375 380 385 390 395]
 [500 505 510 515 520]]
